### ISSUE TITLE
Duplicate events emitted

### ISSUE THREAD

**Issue by davidmw** [monsieurgustav/UE4-OSC#10]
Hi - I'm so thrilled to find this plugin and have it working quickly on 4.9.

I've got the OscReceiver component added to my character BP. On every OnOscReceived, I'm printing the incoming Address and first two floats from the data array.

The plugin seems to be emitting 2 events for every incoming OSC message.

Here are the resulting log entries when I touch an item on a multi-toggle (TouchOSC app) - which deselects and then selects a new button in the button array.

LogBlueprintUserMessages: [CharacterBP_C_16] /basic/stoggle/1/2; 0.0; 0.0
LogBlueprintUserMessages: [CharacterBP_C_0] /basic/stoggle/1/2; 0.0; 0.0
LogBlueprintUserMessages: [CharacterBP_C_16] /basic/stoggle/1/1; 1.0; 0.0
LogBlueprintUserMessages: [CharacterBP_C_0] /basic/stoggle/1/1; 1.0; 0.0

So button 2 is the previous selection and now 1 is selected. If I capture the OSC stream from the TouchOSC app for this control using Pd-extended on my development PC - I get only a single message, as expected, for button 1 and 2 in this case.

Regards,

David

**Comment by monsieurgustav** [comment]
Hi!
Is it new to 4.9? Did you try with earlier version?
I believe that the second message comes from an instance of your class that the engine creates automatically under the hood...
I'm not entirely sure about that, though.
Not sure what is the use of this special instance either!

**Comment by davidmw** [comment]
Ok I've added OSC to a 4.8.3 project.  This one handles the character a bit differently in that it uses a PlayerStart.  The 4.9 project doesn't have PlayerStart - the CharacterBP was placed directly on the level.  Both projects are getting duplicated events.

I'm not convinced the character bp is being instanced twice.  Yes there seems to be two different identifiers printed as the source for my PrintString in the log and one of those matches the temporary Label shown in the WorldOutliner when the game is running.  That is, CharacterBP_C_16 might appear there as CharacterBP16.  But the second version is missing from the WorldOutliner.

Are you emitting from multiple places in the code?

**Comment by monsieurgustav** [comment]
The other one cannot be seen in the outliner, it is internal to the engine. I've seen it using breakpoints in the C++ code. When back home, I'll try to filter out the events of the "default" instances.

Signals are emitted in UOscDispatcher::CallbackMainThread.

**Comment by davidmw** [comment]
Great and thanks!

**Comment by monsieurgustav** [comment]
Actually, I already had some checks on the said default objects...

I think I failed to reproduce your issue. I have no duplicate event, unless I open the blueprint editor on an OSC receiver object. The blueprint editor creates yet another duplicate, that guy may be responsible for your issue.

To help your investigation, I also log registration/unregistration of listeners. They have the "Verbose" level, so you need to add those lines to DefaultEngine.ini to see them.
[Core.Log]
LogOSC=VeryVerbose

Let me know !

**Comment by davidmw** [comment]
The listener log entry isn't verbose after following your instructions above. 

LogOSC:Display: Stop listening
LogOSC:Display: Listen to port 9000

with none of the component registration entries I see in the source.  I have the updated files, a freshly built DLL and even restarted UE4 after confirming ini update.  Not sure what is going on.

But you are correct - if I have the BP editor open in a background tab - I get the duplicates.  So mystery solved after all!

**Comment by monsieurgustav** [comment]
Arguably, it might be interesting to filter out the BP editor instances, but I've no clue how to do it.

**Comment by davidmw** [comment]
I'm implementing the new batch send feature and find that this duplicate event problem is worse than before. Running the project in PIE from the main map with no additional tabs open (no BP editor instances) is now resulting in the duplicate OSC messages from OnOscReceived.

All OSC handling happens in my CharacterBP. If I get the Object Name of the Get Owner of my Capsule Component at Event BeginPlay I get only: CharacterBP_C_1.  If I print the owner string on every Event Tick - I only see: CharacterBP_C_1.  

But at OnOscReceived I always see at least a pair of instances:
CharacterBP_C_1
CharacterBP_C_4

If I have a BP open in another tab then maybe:
CharacterBP_C_1
CharacterBP_C_5
CharacterBP_C_6

So I came up with this work around 

![oscdups1](https://cloud.githubusercontent.com/assets/3413901/13522525/305429d0-e244-11e5-9b0e-7f6c4edfb5eb.PNG)
![oscdups2](https://cloud.githubusercontent.com/assets/3413901/13522524/304feabe-e244-11e5-91ea-e0c95de6f7c8.PNG)

**Comment by monsieurgustav** [comment]
Is it worse? Looks like the same problem as before to me... no?

Trying to understand, tell me if I'm wrong :
- Your OSC receiver is an Actor (a Character ?). It is not a GameMode nor a
Level Blueprint.
- You add an OscReceiverComponent on your actor, you do not subclass
OscReceiverActor.
- You use the capsule component's owner, but it would work with the
OscReceiver or any other component as well.
- Your workaround works because BeginPlay is only called on the "correct"
instance CharacterBP_C_1, not on "hidden" instances.
- The problem of duplication is that OnOscReceived is called even on
"hidden" instances.
- The problem of duplication only happens in the editor, not when running a
package.

I'd really like to tackle down that issue...  : /

**Comment by Dannington** [comment]
Sounds like you need to move the osc handler into its own bp.  Try the player controller.

**Comment by davidmw** [comment]
I say it is worse because I can no longer eliminate the problem by closing all tabs in UE4.

The OSC Receiver is installed on Actor Blueprint.  More accurately - it is added as a component on a Character Blueprint that features a skeletal mesh, collision capsule, and CharacterMovement component.  I do not subclass OscReceiverActor.

Yes I can use owner of OscReceiver - this is a good change for clarity.

Yes, and Yes.

I just tested Standalone Game with my workaround removed and it seems to ignore all Osc activity. I'll need to investigate.

And testing as a Windows Package doesn't immediately work - I have a webcam init error that I need to track down.

**Comment by davidmw** [comment]
Thanks Dannington - that might be a better place for it.
