### ISSUE TITLE
Trouble building for iOS

### ISSUE THREAD

**Issue by davidmw** [monsieurgustav/UE4-OSC#11]
My UE4 project is currently blueprints only. On my PC, I installed the OSC plugin in a fresh C++ project, let the system do the compile, then copied the Plugins folder to my BP project.  This lets me run in PIE and standalone on the PC and OSC works.

I used the same technique on the Mac and it runs fine in PIE. However I'm running into trouble when launching to iOS from the Mac.

When OSC compiles for iPhone SDK 8.4 -- I get a few dozen errors: "cannot use 'throw / try' with exceptions disabled."

I've modified OSC.Build.cs to set bEnableExceptions = false but this didn't change the build errors. Any suggestions you might have for cleaning up this issue and for improving this multi-platform build process would be very useful.

Regards,
David

**Comment by monsieurgustav** [comment]
AFAIK, you're the first one trying to build for iOS...

I found this post:
https://answers.unrealengine.com/questions/85096/how-to-add-boost-library-to-ue-project.html

It looks like "bEnableExceptions = true;" may not be enough for some platforms. Try to add
"UEBuildConfiguration.bForceEnableExceptions = true;"
(bUseRTTI=true; should not be needed)

The other way would be to remove the exception code from the OSCPack library, and replace it by error codes. OSCPack is stable enough, so it's all right to fork in my opinion, but I'll do it only if there is no other way.

Did you try Android too?

**Comment by davidmw** [comment]
I tried one and then both of the additions:
````
            bEnableExceptions = true;
            UEBuildConfiguration.bForceEnableExceptions = true;
            bUseRTTI=true;

            if (Target.Type.HasValue && TargetRules.IsEditorType(Target.Type.Value)) 
            ....
````
But the compiler still reports that exceptions are disabled:
````
osc/OscReceivedElements.h:129:13: error: cannot use 'throw' with exceptions disabled
LogPlayLevel: mono:             throw MalformedPacketException( "invalid packet size" );
````

As for Android - I really need to go there but have not yet configured for it or obtained a device.

**Comment by monsieurgustav** [comment]
Ok, too bad...
I'll remove the exception code ASAP.

In the mean time, comment the throw/try/catch directives in oscpack and the plugin...

**Comment by monsieurgustav** [comment]
Hi !
I pushed the removal of exception code. (using error code instead)
Does that solve your iOS compilation issue ?

Also, I miserably failed to setup a proper Android devenv... If you manage to check the Android compilation as well, that would be awesome !

**Comment by davidmw** [comment]
Hi - yes this solves the compilation issue.  I am now struggling with provisioning (reformatted my development machine) so haven't been able to test execution on iOS yet. And unfortunately I'm not any closer to setting up for Android.

**Comment by monsieurgustav** [comment]
Good luck with that !
Let me know if execution works.

2015-10-23 9:33 GMT+02:00 davidmw <notifications@github.com>:
