### ISSUE TITLE
Multiple of four

### ISSUE THREAD

**Issue by davidmw** [monsieurgustav/UE4-OSC#12]
This issue might be with my OSC source but is worth mentioning as it is odd. The plugin generates OSC Message Error: bundle element size must be multiple of four - on a random basis.

From TouchOSC on the iPad - I've never seen this size error.  I've loaded several factory interfaces and do aggressive mutltitouch testing on a wide variety of controls at rapid pace.

From Lemur on the iPad - many controls seem to result in the size error on an occasional and seemingly random basis.  When this happens my project fails to respond to the tap and it is often the case that 3 or 4 additional size errors will follow within a short time.  Then maybe no errors for many many taps, then another random size error grouping or a solo error.

This happens on my Lemur interface (simple with no scripts or expressions) and on the factory samples.  Even if Lemur is sending occasional bad data the grouping of the error messages from the plugin might suggest that the error status isn't fully reset after the first one.

When I pound on TouchOSC and Lemur and watch for errors in Pd-extended - I get no errors detected.

I've tried creating push buttons on Lemur with different address lengths (from 1 to 6 characters) and they all behave the same way - none giving reliable errors but I can't say that they don't generate errors. There is no single control or address that gives an error each time or even most of the time - so I wonder if the problem is timing related.

**Comment by monsieurgustav** [comment]
Hi,
Someone reported a similar behavior some time ago, using pd. I failed to reproduce the bug, and it looked like a problem in its pd script, so I did not spend much time on the issue...

It may comes from the UE4 UDP socket callback, or the oscpack decoder (I doubt it).

I'll dig into that ASAP. Any more information is welcomed !

**Comment by davidmw** [comment]
Hi - no new info to report but I thought I'd show your plugin in action with a screen shot. I really needed a touch interface for this development utility and the xbox controller just wasn't sufficient.

https://www.facebook.com/RubberRhino/photos/a.1470906816550830.1073741828.1433973600244152/1470906773217501/?type=1&theater

**Comment by monsieurgustav** [comment]
Thanks for sharing !

I use TouchOSC myself extensively; I confirm that I have not met this issue with it.

**Comment by davidmw** [comment]
Additional info on this Multiple of Four issue.  

My original complaint above was with UE4 running on Win7 and with my project running in PIE. I've now tried with the same project running on OSX 10.10.5.

My Lemur based interface is not usable - every iPad touch results in Multiple of Four on the Mac. However I've duplicated the UI with TouchOSC and there it works fine to the Mac.

I spent the big bucks on Lemur in the expectation that scripting will be necessary and for UI components that are missing from TouchOSC - if you are wondering why I don't want to stay with TouchOSC.

**Comment by monsieurgustav** [comment]
UE4-OSC definitely must support Lemur anyway.

I think Lemur uses OSC bundles, whereas TouchOSC doesn't. That may be the
point. I'll have a look next week.

2015-09-21 12:45 GMT+02:00 davidmw <notifications@github.com>:

**Comment by monsieurgustav** [comment]
Actually, I think it is a bug in UE4. I posted a pull-request on their repo.
https://github.com/EpicGames/UnrealEngine/pull/1626

In the mean time, you can report the change in your engine. (no need to recompile the engine, as it is a header only class)

**Comment by davidmw** [comment]
This does seem to fix the problem. Thanks much.

**Comment by monsieurgustav** [comment]
Merged in engine version 4.10.
https://github.com/EpicGames/UnrealEngine/commit/d9c4737ffd6c2a7927865069336bf02fb831ae48
