### ISSUE TITLE
OSC Sender adress

### ISSUE THREAD

**Issue by dabulina** [monsieurgustav/UE4-OSC#14]
Hi!
This is more like request.
Now I'm working with different apps and Bosc is very nice way to communicate between apps, but now I'm at point that my apps are on different computers and i need reconfigure OSC Sender settings in project settings, i need to change my ip each time i change network and i meed rebuild app for specific network. Is there any way to make blueprint for thous settings? 

This plugin is awesome! It must have to be builded in engine by default :)

![screen shot 2015-09-30 at 09 09 40](https://cloud.githubusercontent.com/assets/4573092/10185674/464740cc-6753-11e5-80b0-d0887a783a74.png)

**Comment by monsieurgustav** [comment]
Hi !

Your request is exactly why the send adresses are set in the settings, not
directly on the SendOsc node !
In UE4, settings can be set in INI files, so you don't need to rebuild to
change them.

I think it looks like this:

"Saved\Config\WindowsNoEditor\Engine.ini"

[/Script/OSC.OscSettings]
ReceiveFrom=8000
SendTargets=192.168.1.57:9000


Maybe it worth to have a look at the INI documentation in UE4.

You can't set it in BP, at least not yet.


2015-09-30 8:22 GMT+02:00 dabulina <notifications@github.com>:

**Comment by dabulina** [comment]
Hi!
Hmmm, its not working for me on mac :( 
https://www.youtube.com/watch?v=I3fCjBR1qHs&feature=youtu.be

Im planing to make an android app, with osc plugin and if i can access settings trough blueprint, i can make easy accessible user interface to change settings. 

Thank you very much :)

**Comment by monsieurgustav** [comment]
Can you check the ~/Library/Preferences folder as well ?

https://answers.unrealengine.com/questions/37328/mac-os-x-where-are-the-log-files-in-41.html


2015-09-30 9:46 GMT+02:00 dabulina <notifications@github.com>:

**Comment by dabulina** [comment]
Yes, there are files, but they are empty.

**Comment by monsieurgustav** [comment]
I think they are empty (default values from the build) unless you put
something in them (override).

Spend some time trying to add
[/Script/OSC.OscSettings]
ReceiveFrom=1234
probably to Engine.ini, but it might be another file.

And check the logs (~/Library/Logs, or something) to see if it applies.


2015-09-30 11:31 GMT+02:00 dabulina <notifications@github.com>:
