### ISSUE TITLE
maxmsp to ue

### ISSUE THREAD

**Issue by mijn** [monsieurgustav/UE4-OSC#15]
Hi,
Im trying to get 3 float values (x,y,z) from maxmsp to UE.
I managed to compile your plugin, i set the port and save it as default.
I manage to get your examples blueprints in my project.

Problem is I'm very new to UE, i have no idea how to have a cube (or any basic objects) move based to my data in. Also, can't seems to manage to see in UE if I'm getting the values from maxmsp.
Please help me.. getting rather frustrated.. :)

Im sorry if my question is very basic, hope you can find the time to help though.

**Comment by monsieurgustav** [comment]
Hi,
Did you look at the example files ?
There are a "location sender" and 2 variants of a "location receiver" that should help you a lot !

I use two ways to check if the network works:
- in the BP editor, active connections are highlighted. If the connection after a OscReceived event is highlighted, it's OK.
- in the log, in 'verbose' mode (google it), all received messages are displayed (base64 encoded) in the editor log window.
[Core.Log]
LogOSC=VeryVerbose
