### ISSUE TITLE
OSC port will randomly close and not accept new connections until Unreal restart

### ISSUE THREAD

**Issue by neildufva** [monsieurgustav/UE4-OSC#17]
Has anyone else experienced this? 

Basically the OSC or TCP/IP port will seem to close and not reopen until the application is closed and reopened and then it works fine. Seems to be random in how long it will function before closing... no errors reported and nothing in the logs.. 

We have had this problem on Windows with engine 4.7, 4.8 and 4.9

**Comment by monsieurgustav** [comment]
Does it happen in the editor or in builds ?


What kind of OSC message do you send in ?
Beware that OSC bundles are not handled correctly before 4.10.

2015-12-21 18:05 GMT+01:00 Neil Dufva <notifications@github.com>:

**Comment by neildufva** [comment]
Builds mainly... Don't know if we've ever been able to get it to happen in editor. Guess I'll try doing 4.10, thanks for that info

**Comment by neildufva** [comment]
so the output log continually shows:
LogOSC:Warning: OSC Received Bundle Error: Malformed bundle: element not multiple of 4

**Comment by monsieurgustav** [comment]
Ok, it really looks like the bug that has been solved in 4.10.
See also : https://github.com/monsieurgustav/UE4-OSC/issues/12

Did you try 4.10 ?


2015-12-22 21:37 GMT+01:00 Neil Dufva <notifications@github.com>:

**Comment by neildufva** [comment]
Wow it took a long time to get 4.10 and get the source and then get VS 2015 setup but I think you were right... 4.10 seems to have fixed it somehow, thanks for your help!

Im curious, do you know why this has fixed it? Our guys are dumbfounded, lol.

**Comment by monsieurgustav** [comment]
It was a bug I found in the UDP socket receiver class from the engine :
https://github.com/EpicGames/UnrealEngine/commit/d9c4737ffd6c2a7927865069336bf02fb831ae48
The added "Reader->RemoveAt(Read, Reader->Num() - Read, false);"

Actually, you can even add this line in 4.9 and it works just fine.
You don't even have to recompile the engine, as it is a header only class !
 :)

Can you/I close the issue ?

2015-12-23 16:07 GMT+01:00 Neil Dufva <notifications@github.com>:

**Comment by neildufva** [comment]
thanks bud! yep closing now

**Comment by neildufva** [comment]
Now I have a new issue that happens over time... the log spams this in console and no longer takes in OSC...

LogOSC:Warning: Circular Buffer Full: Message Ignored

**Comment by neildufva** [comment]
maybe its that we are receiving osc packets faster than the system is processing them and sending them to the actor?

**Comment by monsieurgustav** [comment]
Exactly !

Can you open another issue instead of reopening that one ? I will expand on
the new issue.

2015-12-23 21:56 GMT+01:00 Neil Dufva <notifications@github.com>:

**Comment by dabulina** [comment]
The same problem. The game can receive signal around 10 seconds, after that
it closes.
Im using 4.10.1 and i have no idea how to fix it.

**Comment by monsieurgustav** [comment]
Did you check the log ?

2015-12-27 15:22 GMT+01:00 dabulina <notifications@github.com>:

> The same problem. The game can receive signal around 10 seconds, after that
> it closes.
> Im using 4.10.1 and i have no idea how to fix it.
>
> On Thu, Dec 24, 2015 at 10:39 AM, Guillaume Buisson <

**Comment by dabulina** [comment]
Yes,
LogOSC:Warning: Circular Buffer Full: Message Ignored

On Sun, Dec 27, 2015 at 5:36 PM, Guillaume Buisson <notifications@github.com
> wrote:

> Did you check the log ?
>
> 2015-12-27 15:22 GMT+01:00 dabulina <notifications@github.com>:
>
> > The same problem. The game can receive signal around 10 seconds, after
> that
> > it closes.
> > Im using 4.10.1 and i have no idea how to fix it.
> >
> > On Thu, Dec 24, 2015 at 10:39 AM, Guillaume Buisson <

**Comment by neildufva** [comment]
closing and opened new ticket #18 @dabulina @monsieurgustav
