### ISSUE TITLE
LogOSC:Warning: Circular Buffer Full: Message Ignored Unreal 4.10.1

### ISSUE THREAD

**Issue by neildufva** [monsieurgustav/UE4-OSC#18]
Spams in log:
LogOSC:Warning: Circular Buffer Full: Message Ignored

Not sure how to get rid of this...
It doesn't seem like it ever catches up i.e. if it was that we were sending packets too quickly, we can stop sending packets completely and the circular buffer will always stay full. Could potentially be a race condition where it never dequeues whats in the buffer. 

This situation happens intermittently... sometimes it happens quickly, sometimes it takes a long period of time like many hours. Occasionally, we have had a situation where we couldn't get it to happen at all. Its very strange. Could possibly be related to current load on computer resources?

**Comment by neildufva** [comment]
just an update on this, havent got this to happen yet on a packaged version of the game so far, its only been a few hours at the moment. Thanks

**Comment by colossus689** [comment]
Seems like it could be a bug with unreal. Is it possible that the [task](https://github.com/monsieurgustav/UE4-OSC/blob/master/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L189-L193) being created is never actually dispatched; I don't see any sort of code verifying the completion of the generated task or even if the task was successfully created. I could see the circular buffer never dequeueing if the task was for some reason not created or never dispatched at all.

**Comment by neildufva** [comment]
scratch that - able to get it easily to happen even when packaged for shipping :( 

@colossus689 and I are running from source to try to get to the bottom of it

We will keep you updated @monsieurgustav and @dabulina

**Comment by monsieurgustav** [comment]
I think I found the bug, thanks to @colossus689 hint. I fix that and some
other stuff in my way back home, and try to push it tomorrow.

In the mean time, if you cannot wait, modify the line:
https://github.com/monsieurgustav/UE4-OSC/blob/master/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L187
- if(wasEmpty && !_pendingMessages.IsEmpty())
+ if(!_pendingMessages.IsEmpty())

That should do the trick, even if it's overkill.
I'm also interested to know if it works that way.

2015-12-29 17:25 GMT+01:00 Neil Dufva <notifications@github.com>:

**Comment by colossus689** [comment]
@monsieurgustav , definitely overkill but that seems to be doing the trick. Looking more over the code I get the sneaking suspicion this is simply critical code not being protected, specifically `_pendingMessages`.

Consider the case in which `_pendingMessages` is being dequeued in [UOscDispatcher::CallbackMainThread](https://github.com/monsieurgustav/UE4-OSC/blob/bfe838e8a04169fb93774df68a5867acce4a54d1/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L206-L218), on the main thread while `_pendingMessages` is concurrently being accessed with new messages/bundles in [UOscDispatcher::Callback](https://github.com/monsieurgustav/UE4-OSC/blob/bfe838e8a04169fb93774df68a5867acce4a54d1/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L166).

If [this](https://github.com/monsieurgustav/UE4-OSC/blob/bfe838e8a04169fb93774df68a5867acce4a54d1/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L211) condition is met just prior to exiting the function and just then `_pendingMessages` is accessed and a new message/bundle is added then `UOscDispatcher::Callback` could have `wasEmpty = false` and `_pendingMessages.IsEmpty = false` and all following `wasEmpty` would be false never allowing dequeue to occur again.

Properly protecting access to `_pendingMessages` would eliminate that case, not sure if FScopeLock is the proper way of handling it but that seems to be the case for protecting access to `_receivers`.

**Comment by monsieurgustav** [comment]
This commit should fix the issue:
https://github.com/monsieurgustav/UE4-OSC/commit/65ee771d80e1bf2c58b88189de1c72683cca5fd1

Thanks for your help on this issue @colossus689 and @neildufva!

Please, make sure the bug is actually solved and then close the issue!

**Comment by dabulina** [comment]
Still i get the same error message.

This is my workflow:
Im capturing data from kinect camera (all full set, body and face.) And the
end result is fully controlled character by kinect.

I dont know if it helps.

Before i didn't sent so many data, maximum was 4 to 5 floats from arduino,
so i let project to run for one week and it was stable.

And Happy New Year! This plugin awesome, it makes ue4 super interactive. It
should be by the default in engine.


[image: Inline image 2][image: Inline image 3][image: Inline image 1][image:
Inline image 4]

On Thu, Dec 31, 2015 at 1:12 AM, Guillaume Buisson <notifications@github.com

**Comment by colossus689** [comment]
@dabulina can you step through your code and verify that [this](https://github.com/monsieurgustav/UE4-OSC/blob/65ee771d80e1bf2c58b88189de1c72683cca5fd1/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L187-L191) segment of code is eventually executing and the [UOscDispatcher::CallbackMainThread()](https://github.com/monsieurgustav/UE4-OSC/blob/65ee771d80e1bf2c58b88189de1c72683cca5fd1/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L204) is eventually executing ? 

If it is the case and you are simply getting the warning intermittently then I'd probably assume you're simply sending messages at too high a frequency and causing an overflow.

**Comment by dabulina** [comment]
How can i see if the code is executing. Im sorry about this question.  I
very much appreciate your work.

Martins. Dabolins.

**Comment by colossus689** [comment]
@dabulina  judging from your "workflow", I'm assuming you're working on Windows. If you don't already have visual studios project files read this: https://wiki.unrealengine.com/Generate_Visual_Studio_Project

If you do then :
1. In Visual Studio, set your Solution Configuration to "Debug Editor"

2. Build your project.

3. Make sure Unreal editor is running.

4. From the visual studio menu, select Debug > Attach to Process, and choose the running Unreal editor.

5. Run your level from within the editor, and now that the debugger is attached, any breakpoint you've placed in Visual Studio should now be hit.

**Comment by dabulina** [comment]
Hi,

I almost get at point you describe me in instruction. Today im getting so
confused that i made video what im doing. Maybe it will help.
https://www.youtube.com/watch?v=yLRwh9N5ebI

Martins. Dabolins.

**Comment by colossus689** [comment]
That looks like some really interesting work. Is your project open source? If so it would help in figuring out the issue. 

You're pretty close to getting what to what I was asking, you simply need to set breakpoints in your Visual Studio Editor. 

https://msdn.microsoft.com/library/k80ex6de(v=vs.100).aspx

You want to set breakpoints in [UOscDispatcher::CallbackMainThread](https://github.com/monsieurgustav/UE4-OSC/blob/b33fc3bfdf224c4751711430bdb26b6b3a64e918/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L209-L220) and on [this line](https://github.com/monsieurgustav/UE4-OSC/blob/b33fc3bfdf224c4751711430bdb26b6b3a64e918/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L185) of UOscDispatcher::Callback.

only active the breakpoints once you get to the point where Unreal no longer reacts to and you repeatedly get the warning.

**Comment by dabulina** [comment]
Hi,
this project is totally experimental. The idea that i can control virtual
world with my body and expressions, excites me! :)
There i made my break point video report:
https://www.youtube.com/watch?v=Xjk2jHKNYJQ

Probably its right idea to create open this project.
Is this place would be good to open the project:
https://forums.unrealengine.com/forumdisplay.php?11-Work-in-Progress

?


Martins. Dabolins.

**Comment by colossus689** [comment]
Hi @dabulina --

You're doing it right except the last part:

"only active the breakpoints once you get to the point where Unreal no longer reacts to and you repeatedly get the warning."

You've enabled the breakpoints before the problem occurs. Make sure they're disabled until you encounter the problem [linkto: how-to enable/disable breakpoints in VS](https://msdn.microsoft.com/en-us/library/z0x8dx4c(v=vs.90).aspx)

You can make the project open source here on github ([how-to](https://help.github.com/articles/create-a-repo/)) but the forums you mentioned is a good place to make people aware of the project itself.

**Comment by monsieurgustav** [comment]
I pushed a new fix about that issue, hoping it is fixed for good now !
