### ISSUE TITLE
No OSC messages received with UE4 4.11 Preview 8

### ISSUE THREAD

**Issue by hectorC** [monsieurgustav/UE4-OSC#21]
Hello,

The same project works fine in 4.10 but in 4.11 Preview 5 I get no incoming OSC messages (Windows 10). Outgoing messages work fine on both. There are no error messages in the Log other than this one (but apparently unrelated) that appears after playing the project in editor more than once:

LogStats:Warning: MetaData mismatch. Did you assign a stat to two groups? New //STATGROUP_Threads//OSCListener///Thread_23b8_0///####STATCAT_Advanced#### old //STATGROUP_Threads//OSCListener///Thread_2914_0///####STATCAT_Advanced####

**Comment by hectorC** [comment]
Further debugging both projects with VS shows that in UE4.11 UOscDispatcher::Callback never gets called, even though apparently the socket in _socketReceiver was successfully created.

**Comment by hectorC** [comment]
In SocketsBSD.cpp (UE4 Engine) there's a timeout when checking for the socket, line 442:
SelectStatus = select(Socket + 1, &SocketSet, NULL, NULL, &Time);

SelectStatus is then always zero so no reading is performed. Does this point to a UE4 problem and not UE4-OSC?

**Comment by hectorC** [comment]
Preview 7 has been released and not only receiving is still not working but now the plugin fails to build due to changes in IPv4Address.h. In OscSettings.cpp, line 58 fails since the GetValue() method appears to have been removed:

`target->SetIp(address.GetValue());`

It seems that replacing GetValue() with the direct access to the Value variable fixes this.

`target->SetIp(address.Value);`

**Comment by hectorC** [comment]
Still not working in Preview 8 (possibly the last preview version before stable is released).

**Comment by hectorC** [comment]
It seems that, at least in Preview 8, I found the solution. Other than correcting the API changes in IPv4Address, it seems that starting the socket receiver is missing. So after line 51 in OscDispatcher.cpp I just added:

`_socketReceiver->Start();`

And receiving started working.

**Comment by monsieurgustav** [comment]
Hi!
The latest commit should fix it. Like usual: I let you test it and close the issue yourself.

Because there are breaking changes in their API, I also created a branch for "before4.11" development.

Thanks a lot for the investigation: it is super useful to have precise hints in order to maintain the project for a reasonable time investment. :+1:

**Comment by hectorC** [comment]
Awesome! Thank you. The exact same changes in your commit are what I did so it should work.  I'm glad to help with open source software that has been key for developing my project (a Masters thesis). 

Cheers
