### ISSUE TITLE
I think you missed an include file!

### ISSUE THREAD

**Issue by Dannington** [monsieurgustav/UE4-OSC#22]
Thanks for updating the plugin!

When I build I think that

#include "OscMessageStruct.h"

Is missing from the git.

Looking forward to trying this!

Dan

**Comment by monsieurgustav** [comment]
I should never commit at 1am...

2016-03-02 11:58 GMT+01:00 Dannington <notifications@github.com>:

**Comment by monsieurgustav** [comment]
OK, done!
Sorry about that...
