### ISSUE TITLE
Receiving broken (again) for UE4 11 final

### ISSUE THREAD

**Issue by hectorC** [monsieurgustav/UE4-OSC#27]
Hello,

Unfortunately now that UE4 11 final has been released, receiving stopped working again. This time I have no idea what's going on. The listening thread is running but no data is received. The socket seems to be empty every time is checked.

**Comment by hectorC** [comment]
Sorry about the noise, the problem was on my side. It works.

**Comment by monsieurgustav** [comment]
Awesome! :)
