### ISSUE TITLE
Address filtering is unimplemented

### ISSUE THREAD

**Issue by num3ric** [monsieurgustav/UE4-OSC#29]
Any intentions to finish the implementation soon?

**Comment by monsieurgustav** [comment]
Actually, I haven't decided yet.

I thought it was a good idea at the very beginning of the project. The server (receiver) side would also allow '*' and '?' symbols to filter incoming messages.

Then, I read the OSC spec again, and you the routing and pattern matching part of it, and I was puzzled: the server side should not contain any '*', but OSC messages could. So it is basically the reverse of my initial intent...

Support both pattern matching would be a mess, so I must choose between:
- implement the spec, even if I find it awkward and I doubt it is used this way by anyone, or
- be practicle, trash this part of the spec, be haunted by Matt Wright for ever.


What are your expectation for this feature ?

**Comment by sebescudie** [comment]
Hélo, was about to ask the same question.

Say you receive several OSC bundles at the same time on different addresses, is there at this point a way to distinct them ? 
I never managed to do so, but I'm clearly not a blueprint roxxxxor so I may have missed something.

That's what I'd expect from this feature.

**Comment by monsieurgustav** [comment]
Another "better late than never" message: I chose to implement the simpliest version of it, do not receive messages that do not start with the filter.
No *, ?, etc.
It is mainly intended as an optimization. (pre-filter in C++ is faster)
You may use a blueprint "switch" in addition to route the message.
