### ISSUE TITLE
Error in OSC (on Mavericks 10.9)

### ISSUE THREAD

**Issue by The-Skas** [monsieurgustav/UE4-OSC#3]
Hey there (again :P), 

Ive managed to compile and run the OSC plugin on mavericks, yet it seems I get a MalformedBundleException when The Event OSC received gets triggered (when it receives an osc message). 
Specifically on this line:
https://github.com/monsieurgustav/UE4-OSC/blob/master/OSC/Source/OSC/Private/Common/oscpack/osc/OscReceivedElements.cpp#L782 
This is the stack trace: http://pastebin.com/c27eMrxi

Im trying to figure it out, have you been able to run this on mavericks?

Thanks again,

-Salman

**Comment by monsieurgustav** [comment]
Hello !  :)

There are 2 issues here :
- there is an exception
- the exception is not catched, so there is a crash... my bad...
I don't think the OS is involved here.

About the exception being thrown in the first place, please investigate to know if the bundle you provide is well formed. "oscpack", that I use to parse the messages, has been out for quite a long time ; I suspect the error comes from the bundle itself.
How do you generate it ?
Do other software handle it correctly ?

I'll add some error handling code soon.


Guillaume

**Comment by The-Skas** [comment]
Hey Guillaume,

as always thanks! You are absolutely right. I ran a python script to send an OSC message over the same port and your plugin works!

I can't believe i didn't think of that, once again. I tip my head to you :blush: 

Now i have to figure out whats wrong with my other OSC app ^,^

-Salman

**Comment by The-Skas** [comment]
Hey just a note for anyone else who may come across this,

I managed to get my OSC app working by having python capture the message , then forward it to UE4. 

Python seems to read the OSC App just fine, while the plugin doesn't like it. Who knows.

Anyway thanks for giving me the idea!

-Skas

**Comment by monsieurgustav** [comment]
If you could send me the said OSC message, it would be great !

**Comment by The-Skas** [comment]
Hey,
The specific message is the thrown exception "packet too short for bundle element", The OSC message is from a third party application which is the cause of the error. 
I ran windows version of the Osc APP on my other machine and it works fine, the bundling must be messed up for Mavericks version. I'm not sure how to get all the details of the message, only the address and data.
address: /founddata is a float: 1.0 or 0.0
-Skas
Date: Sun, 1 Feb 2015 08:40:29 -0800
