### ISSUE TITLE
Send to group.

### ISSUE THREAD

**Issue by Dannington** [monsieurgustav/UE4-OSC#32]
Rather than using either '-1' to transmit to all OSC targets, or specific ones, i'd like to be able to send to groups of targets.  An idea is we could have the send targets as an int array with a bool for 'send to all'.

**Comment by monsieurgustav** [comment]
The plugin supports multicast.
You can set a multicast address in the "Receive From" setting, and multicast addresses in "Targets".
I've also just added an option to support the useful "multicast loopback".

e.g.
"Group1" is 239.0.0.1:8001
"Group2" is 239.0.0.2:8002
etc.
Several machines can listen to "Group1", all will receive messages sent to "Group1".

It does not match exactly you request, but it is efficient (network wise, it lets the network do the work, not your process) and is already implemented !  ;)

Generally, multicast is enabled on Wifi routers. If you experience issue though, you might want to check your router settings first.
