### ISSUE TITLE
OSC.OscSettings in Saved/Config for packaged builds

### ISSUE THREAD

**Issue by mesamarshall** [monsieurgustav/UE4-OSC#33]
Is there any way we can set the properties inside of DefaultEngine.ini for [OSC.OscSettings] in a packaged build? This would be useful for packaged applications where the send targets may vary.

**Comment by monsieurgustav** [comment]
Hi,
The settings in DefaultEngine.ini can be overridden in the Engine.ini file in the packaged game.

The DefaultEngine.ini of the project is merged into the [ProjectName]-[Platform].pak file. (you can open this binary file and search for "[/Script/OSC.OscSettings]")
The Engine.ini file resides in the package directory, under "/Saved/Config/[Platform]/Engine.ini".

You can also read this:
https://docs.unrealengine.com/latest/INT/Programming/Basics/ConfigurationFiles/
