### ISSUE TITLE
Getting compile errors with version 4.13.2

### ISSUE THREAD

**Issue by pixelomaniak** [monsieurgustav/UE4-OSC#34]
I get the following errors when compiling the plugin:
OscDataElemStruct.h(115): error C2065: 'MakeShared': undeclared identifier,
OscDataElemStruct.h(115): error C2275: 'TArray<uint8,FDefaultAllocator>': illegal use of this type as an expression,
OscDataElemStruct.h(115): error C2065: 'MakeShared': undeclared identifier, 
error C2275: 'TArray<uint8,FDefaultAllocator>': illegal use of this type as an expression

**Comment by monsieurgustav** [comment]
Indead, MakeShared has been introduce in 4.14.

This is fixed in the new branch "before4.14".
