### ISSUE TITLE
4.15 compatibility

### ISSUE THREAD

**Issue by Dannington** [monsieurgustav/UE4-OSC#38]
Hi MonsieurG,

I've had a few people ask about 4.15 on my youtube tutorial page so I thought I'd submit an issue.

I'm not a c++  coder in any way, but I think there must be a new way for the engine to know if it's running in editor or build mode.  I got it to compile by hacking out the checking in the OSC.Build.cs file, but it's not a solution.

I think this is the problem line: (but I have no idea really!!!)

if (Target.Type.HasValue && TargetRules.IsEditorType(Target.Type.Value))

Line41 of OSC.Build.cs

Cheers!

**Comment by monsieurgustav** [comment]
Hi Dannington!
Thanks to feed me with your youtuber issues, it's helpful!

You were right about the bug location: it is now fixed.

**Comment by Dannington** [comment]
Thanks so much!
