### ISSUE TITLE
Build fails under 4.15/Windows 10

### ISSUE THREAD

**Issue by zentralwerkstatt** [monsieurgustav/UE4-OSC#39]
Hi,

Unfortunately, building fails for me, even for the example project.

Engine version: 4.15
OS: Windows 10
Message: `'UnrealBuildTool.TargetRules' does not contain a definition for 'IsEditorType'`

Thanks in advance for any hints on this.

**Comment by monsieurgustav** [comment]
Hi!
Did you get the correct branch?
For 4.15, it would before the "before4.16" branch.

**Comment by zentralwerkstatt** [comment]
Ah, my mistake. Thank you for the quick reply!
