### ISSUE TITLE
Issue with compiling on macOS

### ISSUE THREAD

**Issue by postcom** [monsieurgustav/UE4-OSC#40]
My bad, there are no issues!

**Comment by monsieurgustav** [comment]
Hi!

I suppose you notice the version branches?
For 4.15, you need the "before4.16" branch.

I re-post your question for the record:
"Hello Guillaume. Heard great about this plugin and trying to compile on mac os but run on some issue:
When I try to generate the Xcode project I get these errors:

Messages while compiling /Users/calculator2000/Documents/Unreal Projects/OSC/Intermediate/Build/BuildRules/OSCModuleRules.dll: /Users/calculator2000/Documents/Unreal Projects/OSC/Plugins/OSC/Source/OSC/OSC.Build.cs(5,44) : error CS1729: The typeUnrealBuildTool.ModuleRules' does not contain a constructor that takes 1' arguments (0,0) : error : /Users/Shared/Epic Games/UE_4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe (Location of the symbol related to previous error) UnrealBuildTool Exception: ERROR: UnrealBuildTool encountered an error while compiling source files

As you can see Engine version is 4.15. Is this a real issue?"
