### ISSUE TITLE
Include prebuilt macOS binary or build instructions

### ISSUE THREAD

**Issue by mz2** [monsieurgustav/UE4-OSC#41]
I'm getting the following error message when following installation instructions on macOS 10.11.6:

![screen shot 2017-07-24 at 12 10 00](https://user-images.githubusercontent.com/71363/28520828-070c8842-7069-11e7-8aeb-c3168a83b226.png)

I then checked the contents of UE4OSCPlugin folder and I can see that there indeed are no macOS binaries inside:

```
./Binaries
./Binaries/Win64
./Binaries/Win64/UE4Editor-UE4OSCPlugin.dll
./Binaries/Win64/UE4Editor-UE4OSCPlugin.pdb
./Binaries/Win64/UE4OSC.dll
./Resources
./Resources/Icon128.png
./Source
./Source/UE4OSCPlugin
./Source/UE4OSCPlugin/Classes
./Source/UE4OSCPlugin/Classes/UE4OSCPluginOSCInterface.h
./Source/UE4OSCPlugin/Private
./Source/UE4OSCPlugin/Private/UE4OSCPlugin.cpp
./Source/UE4OSCPlugin/Private/UE4OSCPluginOSCInterface.cpp
./Source/UE4OSCPlugin/Private/UE4OSCPluginPrivatePCH.h
./Source/UE4OSCPlugin/UE4OSCPlugin.Build.cs
./UE4OSCPlugin.uplugin
```

**Comment by monsieurgustav** [comment]
Hi.
I do not provide prebuilt package for any platform.
Did you read the README.md? "Integration" section?

**Comment by mz2** [comment]
You do actually provide a Windows binary in the `UE4OSCPlugin` folder (and I am certain about that because I'm on a Mac that for sure has no ability produce Windows DLLs), which the integration instructions suggest I should copy in the newly created Plugins folder ("Copy UE4OSCPlugin folder to that directory").

**Comment by mz2** [comment]
DUH! Looks like my issue is simpler than that… There's a plugin 'UE4-OSC' and one called 'UE4OSC' and I mixed up the two when googling to find the project GitHub page… I was attempting to install your plugin with instructions for https://github.com/zachrkn/UE4OSC :D

**Comment by monsieurgustav** [comment]
:)
It felt weird indeed.
