### ISSUE TITLE
Receiving from multiple senders

### ISSUE THREAD

**Issue by javierShaman** [monsieurgustav/UE4-OSC#42]
Hi, I was wondering if there is a way for me to receive from multiple senders.
I looked and tried to find a way to do it but couldn't find any. I ended up having to change the code of the plugin creating multiple sockets and sockets receivers. It all seemed to work until I started having this wired error when the _CallbackMainThread_ calls __pendingMessages.Dequeue(message)_. The error actually happens on Array.h, when it calls CopyToEmpty. It throws: unable to access memory, error 0xffffffffff

If you know you know how to resolve this problem, or have a fix for it I'll greatly appreciate it.

Thanks, Javier

**Comment by monsieurgustav** [comment]
Hi,
Generally, receiving from multiple senders is straightforward: the listener listen to a single port (e.g. 7000) and all senders send to the same IP and port, and voilà!
