### ISSUE TITLE
UPDATE FOR 4.17

### ISSUE THREAD

**Issue by sbontly** [monsieurgustav/UE4-OSC#43]
Hi there, just wondering how easy it is to update to 4.17.

Thanks again for your help!

Best
S

**Comment by monsieurgustav** [comment]
Hi!
I'll save some time to do it tonight.
Stay tuned  :)

**Comment by monsieurgustav** [comment]
I pushed the fix for 4.17 on the master branch.

**Comment by sbontly** [comment]
Awesome! Thank you so much. Super useful plugin :)
