### ISSUE TITLE
Commands from a browser

### ISSUE THREAD

**Issue by sinokgr** [monsieurgustav/UE4-OSC#44]
Hi there,
I want to be receive commands from a browser. I found [this](https://github.com/colinbdclark/osc.js) project and I tried a couple of their examples, but I couldn't get it to work with Unreal. Any idea how to do that?
Cheers

**Comment by monsieurgustav** [comment]
Not a clue.

This plugin is not supported in HTML5.
https://github.com/colinbdclark/osc.js could be a basis to support HTML5 here, but I have no plan to do it myself.
But I can offer some support if you feel adventurous!

**Comment by sinokgr** [comment]
correct me if I'm wrong, but I thought that the idea would be that by using Colin's osc.js, I could send data from a page to a node.js socket server and then I would broadcast a new event from the server that UE4-OSC would pick and I would handle it in Unreal but that doesn't seem to work.
Colin has a [repository with examples](https://github.com/colinbdclark/osc.js-examples) and I tried a couple of different servers (UDP/TCP) I couldn't get UE4-OSC to connect. If you could help, that would be great! :)

**Comment by monsieurgustav** [comment]
I thought you wanted to build a HTML5 package of your game, and control it with OSC.

Actually, you have a Win64 build of your game, that you want to control from a node.js process (that happen to be a web server). I got it?

**Comment by sinokgr** [comment]
Yeah, pretty much.
So, I have a Win64 build as you said and a webpage and I want to send events from the webpage to the build and vise versa. To be honest, currently I switched to socket.io, since it's one technology I know how to use, but OSC should have been pretty similar. Even though I moved my R&D to socket.io, I would still be interested to OSC, since one of our partners uses OSC for his communications in UE. If you have any suggestions, why my test failed even when I used the working examples from the osc.js project, feel free to let me know. Have a nice weekend. 😃

**Comment by monsieurgustav** [comment]
Hi!
I've just tried 2 examples for osc.js: "browser" and "udp-browser". I had no issue communicating with them to/from UE4.

"udp-browser" is the more useful, as it is a 2 way communication. Default ports are 7400 for listening and 7500 for sending. After I configured accordingly the UE4-OSC plugin (namely "Receive From" = "7500" and "Send Targets" += "127.0.0.1:7400"), it just worked.

**Comment by monsieurgustav** [comment]
(aside: how do you connect with socket.io?)
