### ISSUE TITLE
Infinite loop when socket fails to send

### ISSUE THREAD

**Issue by HughMacdonald** [monsieurgustav/UE4-OSC#45]
Hi,

I've discovered a bit of an infinite loop occurring when the socket fails to send any data.

The issue occurs [here](https://github.com/monsieurgustav/UE4-OSC/blob/master/OSC/Source/OSC/Private/OscSettings.cpp#L77) when *socket->SendTo()* sets *bytesSent* to -1. This causes *length* to continually increase, meaning that the loop never finishes.

I've found this on 4.17. I was using OSC successfully in 4.16, but on a different machine, so it may be related to my system rather than to the UE4 version. Either way, you may want to fail more gracefully here!

Thanks

**Comment by monsieurgustav** [comment]
Nice catch!
I'm AFK right now, so the fix will wait a little bit.
Or you can file a PR if you feel like it !  :)

**Comment by HughMacdonald** [comment]
Let me see what I can do tomorrow.

Where do you think the best place to flag the error would be? There doesn't seem to be a mechanism in that part of the code at the moment for errors like this.

**Comment by monsieurgustav** [comment]
At the end of the day, the sendto function is used.
https://linux.die.net/man/2/sendto
or
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740148(v=vs.85).aspx

In short : a result of -1 is an error, one must read errno or WSAGetLastError, depending on the platform, to know what's wrong. On mobile, it may be something else.

I don't know if UE4 has a platform independant system error reporting...

I suggest you fix the infinite loop bug, and log a very general message (if byteSent == -1, log and return)
UE_LOG(LogOSC, Error, TEXT("Cannot send OSC: system error"));
Or something like this.

**Comment by HughMacdonald** [comment]
This is what I've come up with so far:
https://github.com/HughMacdonald/UE4-OSC/commit/74a26ee31016e9cc66939c0715dda56654c8c9c6

I need to fix the underlying issue at my end and ensure that the error message is accurate (in my tests it's reported 0.0.0.0:0), but if I can get it reporting the right address, would this work as a PR?

**Comment by monsieurgustav** [comment]
Definitely!
I commented on your commit.

**Comment by HughMacdonald** [comment]
PR can be found at #46
