### ISSUE TITLE
Plugin not compatible with Unreal Engine 4.17.2

### ISSUE THREAD

**Issue by lagauche** [monsieurgustav/UE4-OSC#50]
I'm running 4.17.2 of Unreal Engine on Win 10 64bit. I just tried to install UE-4-OSC for the first time with no luck.

I'm also running Visual Studio 2017 15.4.1

I think I have all the C++ addons installed, but I am a newb.

Any help would be super appreciated.

**Comment by monsieurgustav** [comment]
Hi!
I know that getting into UE4 is not an easy step for a "newb"!  :)

An awesome user of this plugin struggled a lot, and then produced a video tutorial!
https://www.youtube.com/watch?v=GGGs-n-CKtY

Good luck!
