### ISSUE TITLE
4.18.3

### ISSUE THREAD

**Issue by CocoaCup** [monsieurgustav/UE4-OSC#55]
Hello, is it possible to update your plugin to latest 4.18.3 version? I tried to use the master, but I'm missing some of the blueprints, it seems the plugins does not work as it should. Thank you in advance.

**Comment by Dannington** [comment]
I just downloaded this version to upgrade one of my projects from 4.14 and it worked fine.

**Comment by monsieurgustav** [comment]
Hi
You are missing "some" of the blueprints?
So have some of them (which one ?), but not all of them (who's missing ?)

Are you using the provided sample project, or did you add the plugin to you're own project?
(The sample project is probably out of date)

**Comment by CocoaCup** [comment]
For example, I can see OSC character in the, but when I want to edit reciever port settings in the project settings/plugins, there is none of the OSC tab. 

I added the plugin to my project.

**Comment by monsieurgustav** [comment]
I've just tried the plugin with 4.18.3 myself, and it works as expected.

- In the "Modes" window, that normal you can only see OSC Recevier Actor.
- You should see "OSC Receiver component" when you add a component to an actor (blueprint editor or "Details" editor of an object of the world)
- If you disable the "context sensitive" check, you should see "PushInt", "PopFloat", "SendOsc", etc. in the blueprint editor.
- In the project settings, there should be an "OSC"setting  in the "Plugins" section. Do you see it? Is it empty??
- In the "output" log, you should be "Mounting plugin OSC", "LogOSC: Display: Listen to port 8000", "Stop Listening" etc.

**Comment by CocoaCup** [comment]
None of the above listed is in my project, not even the OSC in the Plugins sections, except the OSCCharacter which can be placed.

I added some screenshot to see how it looks in the editor, buw I really don't understand why it's not working.

<a href="https://ibb.co/b42Wac"><img src="https://thumb.ibb.co/b42Wac/OSC.jpg" alt="OSC" border="0"></a> <a href="https://ibb.co/esF68x"><img src="https://thumb.ibb.co/esF68x/OScchar.jpg" alt="OScchar" border="0"></a> <a

**Comment by monsieurgustav** [comment]
You're not looking at the right place for the plugin settings.
The screenshot to provided is the window to enable/disable plugins.
The settings are in the "Project Settings" window. There should be an "OSC"
entry, near "Paper2D" and alikes. Could you confirm?

**Comment by CocoaCup** [comment]
Whoops, the last one didn't upload, but yes, I'm looking in the Project Settings. 
There are only plugins such AVF Media, Houdini Engine, Paper 2D, Oculus, etc visible, but not OCS.

**Comment by monsieurgustav** [comment]
Could you post the "output" log when you open the editor and then when you
play?

**Comment by CocoaCup** [comment]
Sure thing, hope it's the right output log:

> 
MapCheck: Map check complete: 0 Error(s), 0 Warning(s), took 196.166ms to complete.
LogFileHelpers: Loading map 'ThirdPersonExampleMap' took 4.155
LogSlate: Took 0.000692 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Regular.ttf' (155K)
LogSlate: Took 0.000722 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Bold.ttf' (160K)
LogRenderer: Reallocating scene render targets to support 1264x1056 Format 10 NumSamples 1 (Frame:1).
LogLoad: (Engine Initialization) Total time: 42.45 seconds
LogLoad: (Engine Initialization) Total Blueprint compile time: 0.00 seconds
LogExternalProfiler: Found external profiler: VSPerf
LogExternalProfiler: Using external profiler: VSPerf
LogContentStreaming: Texture pool size now 3000 MB
LogAssetRegistry: Asset discovery search completed in 31.0071 seconds
LogCollectionManager: Loaded 0 collections in 0.002025 seconds
LogFileCache: Scanning file cache for directory 'E:/Unreal Projects/OSC/Saved/Collections/' took 0.01s
LogFileCache: Scanning file cache for directory 'E:/Unreal Projects/OSC/Content/Developers/Miriam/Collections/' took 0.01s
LogFileCache: Scanning file cache for directory 'E:/Unreal Projects/OSC/Content/Collections/' took 0.01s
LogCollectionManager: Rebuilt the object cache for 0 collections in 0.000000 seconds (found 0 objects)
LogCollectionManager: Fixed up redirectors for 0 collections in 0.000104 seconds (updated 0 objects)
LogSlate: Took 0.000607 seconds to synchronously load lazily loaded font '../../../Engine/Content/Editor/Slate/Fonts/FontAwesome.ttf' (139K)
LogSlate: Took 0.000941 seconds to synchronously load lazily loaded font '../../../Engine/Content/Editor/Slate/Fonts/DroidSansMono.ttf' (77K)
LogTemp: Repeating last play command: Selected Viewport
LogBlueprintUserMessages: Early PlayInEditor Detection: Level '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel' has LevelScriptBlueprint '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonExampleMap' with GeneratedClass '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdP
ersonExampleMap_C' with ClassGeneratedBy '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonExampleMap'
LogPlayLevel: PlayLevel: No blueprints needed recompiling
PIE: New page: PIE session: ThirdPersonExampleMap (6 Feb 2018 22:42:14)
LogPlayLevel: Creating play world package: /Game/ThirdPersonCPP/Maps/UEDPIE_0_ThirdPersonExampleMap
LogPlayLevel: PIE: StaticDuplicateObject took: (0.278795s)
LogAIModule: Creating AISystem for world ThirdPersonExampleMap
LogPlayLevel: PIE: World Init took: (0.000861s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap to /Game/ThirdPersonCPP/Maps/UEDPIE_0_ThirdPersonExampleMap.ThirdPersonExampleMap (0.280346s)
LogInit: XAudio2 using 'Speakers (Realtek High Definition Audio)' : 2 channels at 48 kHz using 32 bits per sample (channel mask 0x3)
LogInit: FAudioDevice initialized.
LogLoad: Game class is 'GameMode'
LogWorld: Bringing World /Game/ThirdPersonCPP/Maps/UEDPIE_0_ThirdPersonExampleMap.ThirdPersonExampleMap up for play (max tick rate 0) at 2018.02.06-21.42.14
LogWorld: Bringing up level for play took: 0.010670
LogGameMode: Display: Match State Changed from EnteringMap to WaitingToStart
LogGameState: Match State Changed from EnteringMap to WaitingToStart
LogGameMode: Display: Match State Changed from WaitingToStart to InProgress
LogGameState: Match State Changed from WaitingToStart to InProgress
PIE: Play in editor start time for /Game/ThirdPersonCPP/Maps/UEDPIE_0_ThirdPersonExampleMap 0.767
LogBlueprintUserMessages: Late PlayInEditor Detection: Level '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel' has LevelScriptBlueprint '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonExampleMap' with GeneratedClass '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPe
rsonExampleMap_C' with ClassGeneratedBy '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonExampleMap'
LogBlueprintUserMessages: Early EndPlayMap Detection: Level '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel' has LevelScriptBlueprint '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonExampleMap' with GeneratedClass '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPer
sonExampleMap_C' with ClassGeneratedBy '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonExampleMap'
LogBlueprintUserMessages: Late EndPlayMap Detection: Level '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel' has LevelScriptBlueprint '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonExampleMap' with GeneratedClass '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPers
onExampleMap_C' with ClassGeneratedBy '/Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap.ThirdPersonExampleMap:PersistentLevel.ThirdPersonExampleMap'

>

**Comment by monsieurgustav** [comment]
It's the log when you "play" in the editor?
Can you send the log output just after you open the editor ?

**Comment by monsieurgustav** [comment]
Is it the log from "Windows/Developer Tools/Output Log" ?

**Comment by CocoaCup** [comment]
Well, I managed to open the example map and it seems all the required files and plugins are there. I tried to connect my Brainwave device with Brainwave OSC to Unreal Engine, however it looks like the BP is not getting the data.

I added the BP screenshots, maybe I'm doing something wrong.
https://imgur.com/a/GNZ1u

**Comment by monsieurgustav** [comment]
It looks good to me, except your "Select on String" node should probably
use valid OSC address, starting with "/".

To help debugging, you can enable the "Very Verbose" logging (using
"Session Frontend" IIRC) which display all incoming messages (data encoded
in base64)


2018-02-10 20:40 GMT+01:00 CocoaCup <notifications@github.com>:

**Comment by CocoaCup** [comment]
Thank you very much, the missing "/" was the issue, it's working now :) Is there any way how to clamp the values? For examples, I want to limit the attention value only between 30-100 and use it for scaling 3D objects? 

It's working right now, but the scale of the object goes way too high when the attention rises.

Thank you again.
