### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by lagauche** [monsieurgustav/UE4-OSC#58]
I just re-installed a clean Windows 10 and i’m wondering if i can skip VS 2015 and just install 2017 since 2017 is integrated into the newer UE4 builds. 

Will UE4-OSC build all the same with only Visual Studio 2017?

Mainly asking because your install directions only mention 2015.

Thanks!

**Comment by monsieurgustav** [comment]
Hi,
I never tried it, but I see no reason why it wouldn't build correctly...
