### ISSUE TITLE
no date  receive

### ISSUE THREAD

**Issue by sc32024826** [monsieurgustav/UE4-OSC#6]
I want the ue4 to connect to the android mobile ,  and  receive the  sensor dates.   I writed the socket client with  java,when i test to  receive , it's always none date.  can you tell me why?

**Comment by monsieurgustav** [comment]
I did not understand if your UE4 project runs on mobile (Android) or desktop (Windows, MacOSX ?).

Try an OSC monitoring tool, to know if the issue actually comes from the UE4-OSC plugin or from the sender, the network, etc.
I suggest http://www.kasperkamperman.com/blog/osc-datamonitor/
