### ISSUE TITLE
OSC to listen to multiple ports

### ISSUE THREAD

**Issue by PureDenizen** [monsieurgustav/UE4-OSC#60]
You can specify UE4 to listen to one port (project settings), but how do you get the engine (within a blueprint) to listen to different, specified, ports?

**Comment by monsieurgustav** [comment]
Hi,
Listening to several ports is currently not supported.

Could you explain why you need it?

**Comment by PureDenizen** [comment]
Hi, 

Thanks for the quick response. 

I'm using OSC to receive data from MaxMSP and, rather than filtering the data using a type of coding system, I wanted to send each piece of data to different ports. Just for clarity/ease of use. 

The context is this: 
I'm researching the use of a wearable technology called the Myo armband to use within game-engines for the creation of interactive music. This Myo armband is useful because it is novelly equipped with 8 Electromyographic sensors (EMG) which detect muscle activity. I'm therefore using EMG data to map specific hand gestures and then transform those within Unreal. Thus, I want to send each gesture to Unreal via different ports through OSC. Rather than accumulating all the data in one port/channel. 

I hope this is clear! 

Best

**Comment by monsieurgustav** [comment]
Well, in OSC, filtering is supposed to be done using the message's address.
I'm not sure to understand why it's clearer to have anonymous messages (address "/") on several ports than named messages (addresses "/gesture1", "/gesture2") on a single port.

It's not too hard to listen to several ports in the plugin, but it would not be part of the OSC message itself: you could not filter on it.

**Comment by PureDenizen** [comment]
Yes, I guess this is an alternative way of doing so.

Just thought it may be 'easier' and straightforward, per se, to send it via different ports, but the address filtering works just fine! 

Thank you very much for your help.

**Comment by monsieurgustav** [comment]
Glad it makes sense for you!
Also, it's more "inline" with what others do, which is always good! (unless you want to reinvent things)

**Comment by lagauche** [comment]
Hey, 

I am hoping there is some way to open multiple listening ports. @monsieurgustav You had asked for a use case/example/reason. I need UE4 to listen for OSC data streaming in from my phone to control assets and I also need another port to stream in OSC data from an application on the same computer. This is for a live performance. Has there been any new interest in this?

**Comment by monsieurgustav** [comment]
Better late than never: listen to multiple ports is implemented!

**Comment by A1deNxx** [comment]
> 迟到总比不到好：事实发现监听了多个端口！

Hello, sir! Thanks to your Plugin! It is really helpful! I have 2 questions about this😩.

Firstly, I already send six sensor data to MAXMSP from Arduino Mega using the serial port protocol communication, and then I want MAXMSP to send six-track audio data to Unreal 5 to control the game visual effect, is this currently feasible?

Secondly,  does this plugin support that I send the data analyzed by MAXMSP and the music generated by MAXMSP to Unreal 5 at the same time?

Looking forward to your reply！😁
