### ISSUE TITLE
Plugin OSC failed to load when launching

### ISSUE THREAD

**Issue by jaysonh** [monsieurgustav/UE4-OSC#62]
I'm using Unreal 4.20 and the osc module works great in the editor, but when I try launching my project I get an error:

Plugin 'OSC' failed to load because module 'OSC' could not be fround.

Any ideas what is going on here?
thanks!

**Comment by monsieurgustav** [comment]
You mean when you run the "packaged" project?
Did you get some errors during packaging?
Or more details in the runtime log?

**Comment by jaysonh** [comment]
hi yes I am making a packaged project on windows 10 64 bit. When I try running the app I get an error message: 

"LowLevelFatalError [File:Unknown] [Line: 3480] Could not find SuperStruct OscReeiverActor to create OSC_BP_C"

I tried copying and pasting the plugins folder into the package folder but that did not help.

The only warning during the creation of the package is: 

UATHelper: Packaging (Windows (64-bit)):   LogInit: Display: LogOSC: Warning: Settings changed registration failed

I'm not sure how to view a runtime log? Apologies i'm completely new to Unreal.

**Comment by bsubbaraman** [comment]
Old issue since I just ran into & found a fix for a related problem recently: if you're in a Blueprint project, try adding a c++ class as described [here](https://forums.unrealengine.com/development-discussion/engine-source-github/20252-plugin-osc-for-ue4/page14?49627-Plugin-OSC-for-UE4=)
