### ISSUE TITLE
Having Trouble!

### ISSUE THREAD

**Issue by lizzierox** [monsieurgustav/UE4-OSC#63]
Hi Monsieur Gustav! Thank you for making this! 
I'm new to UE4 and a little bit lost. I am trying to use your plug in with BrainWave OSC 0.93 (https://github.com/trentbrooks/BrainWaveOSC) and the Neurosky Mindwave Mobile 2 EEG Headset. I installed your plug in, installed BrainWave (and it works synced with the MindWave), and followed Dan Shirley's UE4OSC Tutorial on YouTube and got some blueprint info from Ethan Wimsett's blog(virtualmentalspace.blogspot.com/2016/07/connecting-to-ue4.html.).
I'm having a hard time getting UE4 to communicate with Brainwave. Here is exactly where I'm at, not sure what I'm missing or doing wrong. When I click simulate no text comes up and the blue print doesn't light up. 
Hopefully you can help! Thank you so much. 

![bluetooth settings 11_10_2018 3_28_06 pm](https://user-images.githubusercontent.com/44933612/48307231-43ca7280-e4fd-11e8-8c52-77c6c907e31e.png)
![connected 11_10_2018 3_14_57 pm](https://user-images.githubusercontent.com/44933612/48307218-18e01e80-e4fd-11e8-8877-0de3bf447730.png)
![neuroproj - unreal editor 11_10_2018 3_14_26 pm](https://user-images.githubusercontent.com/44933612/48307219-18e01e80-e4fd-11e8-8faf-73b2048be435.png)
![oscbp 11_10_2018 3_12_55 pm](https://user-images.githubusercontent.com/44933612/48307220-18e01e80-e4fd-11e8-9b29-f05f3ecf3b67.png)
![oscbp 11_10_2018 3_13_18 pm](https://user-images.githubusercontent.com/44933612/48307221-18e01e80-e4fd-11e8-972e-290a3ca5073d.png)
![project settings 11_10_2018 3_14_18 pm](https://user-images.githubusercontent.com/44933612/48307222-18e01e80-e4fd-11e8-955c-033e5940c882.png)

**Comment by lizzierox** [comment]
That was it!!! Thank you!!!!

**Comment by lizzierox** [comment]
Thank you so so much for help, I’m sorry to bother you again! I’m now trying to use the information collected from the OSC plug in and use it to create a conditioned response: if the value is more than 70 I want it to play a level sequence but if it is less I want it to pause the level sequence. This is where I’m at now and it is not playing? Any ideas? 

![0](https://user-images.githubusercontent.com/44933612/48679225-7a7a3b80-eb42-11e8-9b58-55c402ec7443.jpeg)

**Comment by monsieurgustav** [comment]
I think you should watch some more tutorials about Blueprint! :)
Here, the "exec" pin of "Branch" and "Play" nodes are not connected, so they never will be executed. You should probably connect the OSC received event out "exec" pin to Branch.
