### ISSUE TITLE
Biometric Algorithms available?

### ISSUE THREAD

**Issue by dkhalili** [monsieurgustav/UE4-OSC#66]
I was wondering if there will be an update to add the newer algorithms Neurosky released. I see Attention, Meditation and blink, but there are far more algorithms out now that would be extremely useful. Is there something I can do to add the to the project or will there be an update somewhat soon?

The following is a link to the list of algorithms: http://neurosky.com/biosensors/eeg-sensor/algorithms/

Thank you and amazing plugin! Appreciate all the help.

**Comment by Dannington** [comment]
You will need to decide this information yourself.  OSC is just a communication protocol.

**Comment by Dannington** [comment]
Whoops - not decide, decode.

**Comment by monsieurgustav** [comment]
Absolutely!
OSC is not a domain specific protocol.
