### ISSUE TITLE
Converting between types

### ISSUE THREAD

**Issue by HughMacdonald** [monsieurgustav/UE4-OSC#68]
I wanted to put this in as an issue for discussion before doing anything that could be pushed through as a pull request.

I was recently hit with a situation where I thought that I was receiving an `int` from my OSC app, but it was actually coming through as a `float`.

I'm proposing adding the following methods to OscDataElemStruct:

    ToIntValue()
    ToFloatValue()
    ToBoolValue()
    ToStringValue()
    ToBlobValue()

What each of these would do would be to get the actual value, and do what it can to convert it to the value that is being requested.

Note that in what follows, I'm referring to `bool` as a numerical value.

I think that the combination of numerical values should be reasonably obvious what they would do - either convert the value or truncate it, and `ToBoolValue()` should give `true` if the numerical values are not 0.

For strings, I'm thinking that the conversion from string to numerical should use `atoi` (or equivalent). Alternatively, it could return the length of the string.

For blobs, I'm less sure. It could be the bitwise data that was there, or we could just not implement `ToBlobValue()`, and for the others, if the data is actually a blob, return the default value.

What do you think?

**Comment by HughMacdonald** [comment]
And now I feel like an idiot, as it seems that this is already in there with `GetValue<T>()`. Please ignore all of the above!

**Comment by monsieurgustav** [comment]
Yes! There are basic conversion between types.
See UOscFunctionLibrary::PopFloat & UOscFunctionLibrary::AsFloat

Still, as you came up with this idea, I guess you had a crash or something?
