### ISSUE TITLE
Not compiling on version 4.21.2

### ISSUE THREAD

**Issue by LawrenceSelly** [monsieurgustav/UE4-OSC#69]
Plugin refuses to compile on Unreal version 4.21.2

```
[2019.03.07-15.21.34:217][481]CompilerResultsLog: Error: D:/Unreal Projects/Summer_99_ForIgloo/Plugins/OSC/Source/OSC/Private/Common/OscDataElemStruct.h(7)  : Error: struct: 'OscDataElemStruct' conflicts with another type of the same name defined at D:\Unreal Projects\Summer_99_ForIgloo\Plugins\OSC\Source\OSC\Public\Common\OscDataElemStruct.h(6)
```

**Comment by monsieurgustav** [comment]
For some reason, you have 2 OscDataElemStruct.h files in the plugin sources. Something went wrong went you installed it.
Remove the Plugins\OSC\Source folder content and download the source again.

**Comment by LawrenceSelly** [comment]
It was a direct download and install, I did not modify anything and there was no plugin folder before I created it for this.

Fresh basic project too.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by monsieurgustav** [comment]
Did you try?

**Comment by algala2** [comment]
I have the same issues:

Error	struct: 'OscDataElemStruct' conflicts with another type of the same name defined at D:\UE_4.21Pro\MyProject\Plugins\OSC\Source\OSC\Public\Common\OscDataElemStruct.h(6)	MyProject	D:\UE_4.21Pro\MyProject\Plugins\OSC\Source\OSC\Private\Common\OscDataElemStruct.h	7	
with regards AlexG

**Comment by monsieurgustav** [comment]
OscDataElemStruct.h only exists in OSC/Source/OSC/Public/Common/.
Previously, it was in OSC/Source/OSC/Private/Common/.

Your error means you copy pasted the plugin source onto an old version of the plugin. Remove the OSC folder completely and start again!

**Comment by algala2** [comment]
Thank You -it works now
AlexG
