### ISSUE TITLE
4.22 Fails to Compile on Android

### ISSUE THREAD

**Issue by Aeromix** [monsieurgustav/UE4-OSC#70]
I am trying to compile on 4.22 for Android and it fails.

It compile successfully on Windows no problem, any help would be appreciated,

Thank you,

-Brandon!

![image](https://user-images.githubusercontent.com/10228091/59156161-baa3fb80-8a4b-11e9-8c57-10fe755fb6d6.png)

**Comment by monsieurgustav** [comment]
Hi,
I (finally) pushed a commit that could fix your build issue.
Feel free to try and report success or failure here!

**Comment by Aeromix** [comment]
This has solved the issue! Thank you so much!
