### ISSUE TITLE
UE4.23: Plugin doesn't work in packaged application

### ISSUE THREAD

**Issue by lpmorin** [monsieurgustav/UE4-OSC#71]
The plugins does compile in UE 4.23 and works great in the editor but when I tried to package and run the executable, I get the Assertion failed: CachedSocketSubSystem... error.

Thanks

**Comment by kirill6764** [comment]
> The plugins does compile in UE 4.23 and works great in the editor but when I tried to package and run the executable, I get the Assertion failed: CachedSocketSubSystem... error.
> 
> Thanks

Yeah. I have same issue...

**Comment by Hextionsh0t** [comment]
Same here :(

**Comment by eusebijucgla** [comment]
Seems to work on 20.1, with the branch of "before4.21"

**Comment by monsieurgustav** [comment]
Hi guys.
I'm really super busy, I could not find any time to fix it yet...

**Comment by monsieurgustav** [comment]
I've just pushed a fix!
Tell me if it works for you too...

**Comment by vvox-mark** [comment]
@monsieurgustav I can confirm builds are now working on our end. Thank you for the fix!
