### ISSUE TITLE
Packaging Error in UE 4.23

### ISSUE THREAD

**Issue by appmechanic** [monsieurgustav/UE4-OSC#72]
Hello, 

I am getting packaging error in 4.23. 

It shows: 
Assertion Failed : CachedSocketSubsystem != nullptr && *Networking module not loaded and initialized"

[File: Runtime\Networking\\Public\Interfaces\/IPv4/ipV4eNDPOINT.H\[Line: 105]

**Comment by monsieurgustav** [comment]
Hi,
This has been fixed in the latest commit "crashfix: IPv4Endpoint should be initialized before use".

**Comment by appmechanic** [comment]
Thanks.

**Comment by lesterxmn** [comment]
same problem with ue4 4.25! but where can i initialize the IPv4Endpoint?
