### ISSUE TITLE
Can i change port at runtime?

### ISSUE THREAD

**Issue by LanslotChung** [monsieurgustav/UE4-OSC#74]
i have to run same app on one computer,so i have to change each app's receive port.

**Comment by monsieurgustav** [comment]
Hi, sorry for the very late reply.
You can't change the port at runtime. Someone asked for it before, but the consequences would be larger than it seems, so I do not plan to do it.
To fix your probem, the port is a config option: so you can run the same application on the same machine with a different config file to assign a different port to them.
I hope it helps.
