### ISSUE TITLE
string arguments are clipped if end by "_0" "_1" "_2"...

### ISSUE THREAD

**Issue by vital-net** [monsieurgustav/UE4-OSC#75]
Hello everyone,

I realized that OSC messages with string arguments are clipped at the end.
For example "/EDIT slider_1" become "/EDIT slider"

Same from _0 to _9
After that _10 and beyond are not clipped.
not an issue with letters _a _b _c etc
Not a major issue but worth to notice.

It's interesting to note that when printing the content of the send OSC messages in unreal the string argument is complete. But when using an external tool to read the message, it's clipped, and I tried with 3 different software.

Thank you for this amazing plugin !

**Comment by monsieurgustav** [comment]
Hi,
I think it has to do with the old choice I made (for performance reasons) to use FName type to store strings. At the time, I failed to notice a consequence: strings are clipped (after 256 chars IIRC). I guess you just found another consequence...

For people having issue with my partially failing OSC strings implementation, I suggest to use "blobs" that are free of known issue.

Cheers
