### ISSUE TITLE
Crash when launching for Unreal 4.23.1

### ISSUE THREAD

**Issue by bsubbaraman** [monsieurgustav/UE4-OSC#76]
Using Unreal 4.23.1 on a Mac running Mojave, the plugin works in the editor but crashes on launch with the error "Could not find SuperStruct OscReceiverActor to create BP_OSC_C". This error seems to be similar to #62. 

Any ideas on how to fix this (or am I forgetting to do something prior to launch)?
Thanks for any help!
Assertion failed: [File:/Users/build/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/Serialization/AsyncLoading.cpp] [Line: 3610] Could not find SuperStruct OscReceiverActor to create BP_OSC_C

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x1065d8d6b (filename not found) [in UE4Game]
FMacErrorOutputDevice::Serialize(wchar_t const*, ELogVerbosity::Type, FName const&) Address = 0x1066e86b3 (filename not found) [in UE4Game]
FOutputDevice::LogfImpl(wchar_t const*, ...) Address = 0x1067a1169 (filename not found) [in UE4Game]
AssertFailedImplV(char const*, char const*, int, wchar_t const*, __va_list_tag*) Address = 0x10674ce1d (filename not found) [in UE4Game]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x10674cf6b (filename not found) [in UE4Game]
FAsyncPackage::EventDrivenSerializeExport(int) Address = 0x106a30bc5 (filename not found) [in UE4Game]
FAsyncPackage::ProcessImportsAndExports_Event() Address = 0x106a29e1d (filename not found) [in UE4Game]
FAsyncPackage::Event_ProcessImportsAndExports() Address = 0x106a296f2 (filename not found) [in UE4Game]
FAsyncLoadEventQueue::PopAndExecute(FAsyncLoadEventArgs&) Address = 0x106a38767 (filename not found) [in UE4Game]
FAsyncLoadingThread::ProcessAsyncLoading(int&, bool, bool, float, FFlushTree*) Address = 0x106a36c98 (filename not found) [in UE4Game]
FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*) Address = 0x106a4140a (filename not found) [in UE4Game]
FAsyncLoadingThread::TickAsyncLoading(bool, bool, float, FFlushTree*) Address = 0x106a402dd (filename not found) [in UE4Game]
FlushAsyncLoading(int) Address = 0x106a44d38 (filename not found) [in UE4Game]
LoadPackageInternal(UPackage*, wchar_t const*, unsigned int, FLinkerLoad*, FArchive*, FUObjectSerializeContext*) Address = 0x106c37523 (filename not found) [in UE4Game]
LoadPackage(UPackage*, wchar_t const*, unsigned int, FArchive*, FUObjectSerializeContext*) Address = 0x106c349bc (filename not found) [in UE4Game]
UEngine::LoadMap(FWorldContext&, FURL, UPendingNetGame*, FString&) Address = 0x10931030c (filename not found) [in UE4Game]
UEngine::Browse(FWorldContext&, FURL, FString&) Address = 0x10930c838 (filename not found) [in UE4Game]
UGameInstance::StartGameInstance() Address = 0x108a41a0c (filename not found) [in UE4Game]
UGameEngine::Start() Address = 0x108a29c2e (filename not found) [in UE4Game]
FEngineLoop::Init() Address = 0x105eb1bb9 (filename not found) [in UE4Game]
GuardedMain(wchar_t const*) Address = 0x105ec1766 (filename not found) [in UE4Game]
-[UE4AppDelegate runGameThread:] Address = 0x105ec9baf (filename not found) [in UE4Game]
-[FCocoaGameThread main] Address = 0x1066e7801 (filename not found) [in UE4Game]
Unknown() Address = 0x7fff37a370e2 (filename not found) [in Foundation]
_pthread_body Address = 0x7fff619322eb (filename not found) [in libsystem_pthread.dylib]
_pthread_start Address = 0x7fff61935249 (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff6193140d (filename not found) [in libsystem_pthread.dylib]

**Comment by bsubbaraman** [comment]
I was in a Blueprint project- fixed by adding a c++ class and building from source as mentioned in the UE4 forum thread [here](https://forums.unrealengine.com/development-discussion/engine-source-github/20252-plugin-osc-for-ue4/page14?49627-Plugin-OSC-for-UE4=)

**Comment by monsieurgustav** [comment]
Yes.
I know it would help to provide pre-built versions of the plugin, but I wouldn't have the time to maintain them...
