### ISSUE TITLE
It doesn't support version 4.24

### ISSUE THREAD

**Issue by YasserDante** [monsieurgustav/UE4-OSC#78]
I tried but couldn't build the plug-in for UE4.24...:(

**Comment by todernst** [comment]
I couldn't build either. Got the following errors when using 4.24 source
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(1): error : Expected OscOutboundPacketStream.h to be first header included.
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Private\Common\oscpack\osc\OscReceivedElements.cpp(1): error : Expected OscReceivedElements.h to be first header included.
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Private\Common\oscpack\osc\OscTypes.cpp(1): error : Expected OscTypes.h to be first header included.
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Private\Receive\OscDispatcher.cpp(1): error : Expected OscDispatcher.h to be first header included.
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Private\Receive\OscReceiverInputKey.cpp(1): error : Expected OscReceiverInputKey.h to be first header included.
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Private\OscSettings.cpp(1): error : Expected OscSettings.h to be first header included.
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Public\Common\OscFunctionLibrary.cpp(1): error : Expected OscFunctionLibrary.h to be first header included.
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Public\Receive\OscReceiverActor.cpp(1): error : Expected OscReceiverActor.h to be first header included.
1>E:\Unreal Projects\Compiler424\Plugins\OSC\Source\OSC\Public\Receive\OscReceiverComponent.cpp(1): error : Expected OscReceiverComponent.h to be first header included.

**Comment by monsieurgustav** [comment]
Hi,
I already checked the support for 4.24 (not from source though) and it works for some people.
cf. https://github.com/monsieurgustav/UE4-OSC/issues/77

If it does not work for you, I need more info...

**Comment by todernst** [comment]
![OSCUE4424](https://user-images.githubusercontent.com/2394149/74682812-1dca5e00-5195-11ea-8953-b652444678d8.png)

**Comment by lesterxmn** [comment]
4.25 works on editor, make a windows build and cant run
 LogPlayLevel: Error: [2020.11.23-18.59.50:559][  0]LogWindows: Error: Assertion failed: CachedSocketSubsystem != nullptr && "Networking module not loaded and initialized" [File:d:\002_games\ue_4.25\engine\source\runtime\networking\public\Interfaces/IPv4/IPv4Endpoint.h] [Line: 105]
![error](https://user-images.githubusercontent.com/6243086/100134040-d4eeb680-2e44-11eb-8092-8f515a2a45e4.JPG)

**Comment by monsieurgustav** [comment]
This issue is about 4.24 support.
If you have a 4.25 issue, please open a new one.
