### ISSUE TITLE
Basic Blueprint demo

### ISSUE THREAD

**Issue by YanYas** [monsieurgustav/UE4-OSC#8]
Hi Gustav,

I come from using vvvv and I'm using Blueprint for the first time (actually yesterday, just going through the onboard tutorial guide). While the blueprint system is great it presents a very steep llearning curve for me at the moment. I've only just found out where to change the port setttings for the plugin, which took me all day

I've managed to compile your plugin (took a few hours), and I've managed to add a OSCReceiverComponent to my Blueprint by accident.

What I would like to know is just one, and the simplest way, to move an object from vvvv.

So far I don't understand how to hook up BP to use you OSC input. I'm not sure if There is anypoint in making inputs from the plugin settings at this point or if that simply complicates matters. I only want to send one float to the x-axis of a cube and then build me knowledge up from there.

Your answer may be to go back and learn Blueprint but your usage guide is a little too sparse for me (and other people I know with more UE4 experience) to follow. I know that I need more experience with UE4 but a screen shot of a freshly made BP graph that goes from 'event' to transform or target object could be illuminating. Your help here would would be a Godsend.

Thanks,

Yas

**Comment by monsieurgustav** [comment]
Hi !
Did you check the "Examples" folder ?
You might be interested in the "LocationReceiver_Component.uasset" file, which does basically what you want. (just drop it in your project's "Content" folder)

If I were you, I would not go to "Inputs" right now. They are a little bit awkward today.
Then you can either add an OscReceiverComponent to an existing actor (what you did) or create a new actor with OscReceiverActor as a parent class. It is just a matter of "style".

If the example file helped you, I let you close the issue.
Cheers,
Guillaume

**Comment by YanYas** [comment]
Hi Gustav,

Yeah this helps, I'm really close. Data is definitely being sent and I even attached a 'pring string node to the Make vector result that is reading out correctly. however (and this isn't an issue with the plugin now, just a bit of general blueprint ignorance) I don't know how to apply the Target...

Okay I got it. i used your unmodified example and added a mesh as a target correctly so now it behaves as intended. Excellent work dude!
