### ISSUE TITLE
Have problem building on 4.24.3

### ISSUE THREAD

**Issue by serourian** [monsieurgustav/UE4-OSC#82]
Getting this message on Visual Studio 2015:

1>------ Build started: Project: OSC, Configuration: Development_Editor x64 ------
1>  Creating makefile for OSCEditor (game project files are newer)
1>UnrealBuildTool : error : Plugin 'OSC' (referenced via default plugins) does not contain the 'OSC' module, but lists it in 'C:\Users\serou\Documents\UnrealOsc\OSC\Plugins\OSC\OSC.uplugin'.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(37,5): error MSB3075: The command ""C:\Program Files\Epic Games\UE_4.24\Engine\Build\BatchFiles\Build.bat" OSCEditor Win64 Development -Project="C:\Users\serou\Documents\UnrealOsc\OSC\OSC.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by monsieurgustav** [comment]
Hi,
Not sure, but I guess the builder is confused because your project is called "OSC" as well.

**Comment by serourian** [comment]
Yes, that was correct. Thank you very much. Problem Solved.
