### ISSUE TITLE
UTF-8 for Arabic Support

### ISSUE THREAD

**Issue by serourian** [monsieurgustav/UE4-OSC#84]
Hi, I'm sending UTF-8 osc via my own c# program to unreal, but can't read on unreal. Is there a way to support UTF-8 to send arabic strings ?
regards.

**Comment by monsieurgustav** [comment]
OSC has no knowledge of UTF8, it's just bytes.
You must tell UE4 to interpret received bytes as a UTF8 stream somehow. I would try to use the OSC "blob" type, which gives an byte array to work with.

**Comment by serourian** [comment]
thx for the fast reply very much.
Does the output of the Pop String hold utf8 ??? Is it possible to add a new " Pop UTF8 string" receiver function in osc ??
The controllers we have programmed are all huge and many, it is impossible for us to change everything back to blob . . . .

**Comment by monsieurgustav** [comment]
Unfortunately, it won't be that easy:
In this plugin, OSC strings are stored as FName. I don't know if FName is capable of storing UTF8, that you must try.

There may be a bug when copying OSC string to FName here:
https://github.com/monsieurgustav/UE4-OSC/blob/eaec411eca94f50aae1fbc9451535ae08e4c87e9/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp#L137
Currently, FName is constructed using a char*. One might need to use wchar_t* to support UTF8?

Once stored in FName, it is get/set here:
https://github.com/monsieurgustav/UE4-OSC/blob/eaec411eca94f50aae1fbc9451535ae08e4c87e9/OSC/Source/OSC/Public/Common/OscDataElemStruct.h#L92

**Comment by serourian** [comment]
thank you very much
