### ISSUE TITLE
Plugin conflicts with Epic OSC plugin at build time.

### ISSUE THREAD

**Issue by Dannington** [monsieurgustav/UE4-OSC#85]
I can only build a project if I remove Epic's plugin from the engine plugin folder - otherwise there's an a build fail error:

System.ArgumentException: An item with the same key has already been added.

It sucks that Epic just rode over this plugin - hope it's fixable - I have no idea!

**Comment by monsieurgustav** [comment]
I had an issue that I solved renaming OSC.uplugin to UE4-OSC.uplugin.
Could you confirm it works for you too?

**Comment by gaborpapp** [comment]
I can confirm that renaming the .uplugin file works in 4.25.3.

**Comment by monsieurgustav** [comment]
OK, thanks!
I pushed the renaming, so it should be fixed.
