### ISSUE TITLE
Assertion Failed error at runtime UE4.25

### ISSUE THREAD

**Issue by Arphalax** [monsieurgustav/UE4-OSC#86]
Hi,

I am having an issue with a package built in 4.25 it gives the following error at runtime:

Assertion Failed : CachedSocketSubsystem != nullptr && *Networking module not loaded and initialized"

[File: Runtime\Networking\Public\Interfaces/IPv4/ipV4eNDPOINT.H[Line: 105]

The packaging ends successfully but once I try to run the program, it fails with that error. 
we are migrating some of the code from a previous version of the engine (4.21 to 4.25) and I understand there is an epic's implementation now, I guess the problem is related to that, so one of my questions is, can we use the plugin implementation instead of epic's some how?  this will save us a massive amount of time.  

Thank you for your time.

**Comment by monsieurgustav** [comment]
Hi!
First: you can for sure use this plugin over the Epic's one, that's what I do personnaly.

The issue "Networking module not loaded and initialized" should already be fixed... Do you have the latest version of the plugin?

**Comment by Arphalax** [comment]
Yes I think I have the last version of the plug in....  

I am a bit at lost here, and lost track of everything I tried to fix it with no luck. 

is there any steps I have to take to overrides epic's implementation? .. is this error has anything to do with that?

**Comment by monsieurgustav** [comment]
No, it should be unrelated...
Did you activate the Epic's plugin?

In OscSettings.cpp, do you spot the line "FIPv4Endpoint::Initialize();"?

**Comment by Arphalax** [comment]
Epic's plugin disappears once I add the this plugin implementation..  

I am going to check if the line you mention is not there for some reason.

**Comment by Arphalax** [comment]
ok, I installed the latest version again just to make sure, and when I try to build the project on Visual studio I get this error, which makes me think is trying to use the epic's implementation, but I am almost sure I am wrong or doing something wrong. 


Error		Plugin 'OSC' (referenced via MyProject.uproject) does not contain the 'OSC' module, but lists it in 'I:\Unreal425\UE_4.25\Engine\Plugins\Runtime\OSC\OSC.uplugin'.	

then the build fails.

**Comment by monsieurgustav** [comment]
Hum, it makes some sense: I had to rename this plugin to "UE4-OSC" so it doesn't clash with the Epic's one. Now "OSC" refers to Epic's.
Then, you should probably edit your uproject file to reflect this change.

**Comment by Arphalax** [comment]
yes, I think I got it now...  the epics implementation doesn't disappears now that the plugin is named differently so it should be disabled manually, I guess I didn't had the latest version after all...  will make more test to make sure everything is working now, I am making test with a partial project files, so not sure if this is working. will get back if there is more issues or hopefully to let you know if I got it working...   thank you so much for your time I appreciate it.

**Comment by Arphalax** [comment]
Thank you!! that worked.

At some point we did update the plugin with no luck (not sure why) but this time it worked fine, maybe we missed some step or something changed in the project.       All good so far, thanks.
