### ISSUE TITLE
4.26 version

### ISSUE THREAD

**Issue by dpredie** [monsieurgustav/UE4-OSC#87]
Is it possible to compile this for 4.26? Epic's OSC plugin has bugs

**Comment by monsieurgustav** [comment]
Hi, Yes, it works with 4.26. Guillaume Envoyé depuis mon téléphone Huawei-------- Message original --------De : dpredie ***@***.***>Date : dim. 28 mars 2021 à 04:34À : monsieurgustav/UE4-OSC ***@***.***>Cc : Subscribed ***@***.***>Objet : [monsieurgustav/UE4-OSC] 4.26 version (#87)
Is it possible to compile this for 4.26? Epic's OSC plugin has bugs

**Comment by dpredie** [comment]
hi @monsieurgustav 

thanks for the reply, i tried making a C++ project in 4.26, create Plugins Folder and put the "OSC" folder in there and hit generate VS files, but when i open the VS .sln project in the VS explorer the plugins folder is nowhere to be found.

**Comment by dpredie** [comment]
Hi, it actually compiled now. the issue is I was following the Youtube tutorial to put OSC folder in the Plugins, whereas you need to put the whole UE4-OSC folder to the Plugins folder.

**Comment by monsieurgustav** [comment]
I had to rename this plugin, originally named "OSC", to "UE4-OSC" to fix 
conflicts with the now official OSC plugin.


Le 28/03/2021 à 22:52, dpredie a écrit :

**Comment by dpredie** [comment]
using UE4-OSC folder instead works, thanks!
