### ISSUE TITLE
OSC not working in Android

### ISSUE THREAD

**Issue by Voxven-Venox** [monsieurgustav/UE4-OSC#90]
I have used this plugin to sucessfully package for windows and OSC works great. But if i try to package for android the OSC is not working, am i missing something?

**Comment by monsieurgustav** [comment]
Hi,
Sorry for the very late answer, 2 babies stole my focus 2 months ago...

I don't use the plugin on Android myself, so I won't help much. But I read someone using it for Android, while the official plugin does not work currently.

Check the logs first, then maybe the Android permissions for network?

**Comment by monsieurgustav** [comment]
@Zack1501 Did you do anything remarkable so it works on Android?
